#port => default: 8080 => 9090 or 8081
#spring => 데이터베이스 세팅 (datasource)
server: 
  port: 9090
  servlet:
    context-path: /
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: oracle.jdbc.driver.OracleDriver
  jpa:
    database: oracle
    properties:
      hibernate:  
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        user_sql_comments: true
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:templates/
    suffix: .html
    mode: HTML
# mybatis
mybatis:
  type-aliases-package: com.sist.web.vo
  mapper-locations: mybatis/mapper/*.xml
# logging
logging: 
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
# security
# spring ai
# websocket = kafka(카프카)
