name: Deploy Git Action
# 언제부터 배포를 시작 = master에서 push할때마다 배포
on: 
  push:
    branches:
      - master

# 작업 지시
jobs:
  deploy:
    runs-on: self-hosted # 현재 Ubuntu에 배포
    
    # 어떤 순서로 진행할지
    steps:
      # 1. 소스 코드 다운로드 = clone
      - uses: actions/checkout@v4
      
      # 2. JDK 21버전인지 확인
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      # 환경 설정
      - run: |
         echo "========================="
         echo "환경변수 설정"    
         echo "========================="
         rm -rf .env
         touch .env
         echo "DB_URL=${{ secrets.DB_URL }}" >> .env
         echo "DB_USERNAME=${{ secrets.DB_USERNAME }}">> .env
         echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}">> .env
         echo ".env 저장완료"
         
      # 3. gradlew 권한 부여
      - run: chmod +x gradlew
      
      # 4. 빌드 
      - run: ./gradlew clean build -x test
      
      # Docker 이미지 생성
      - run: docker build -t pinia-app .

      # Docker tag 생성
      - run: docker tag pinia-app ${{secrets.DOCKER_USERNAME}}/pinia-app:latest
      
      # Docker Hub 연결
      - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin

      # Docker Hub Push
      - run: docker push ${{secrets.DOCKER_USERNAME}}/pinia-app:latest

      # 기존의 컨테이너 종료
      - run: docker compose down

      # 최신 Docker 실행
      - run: docker compose pull

      # Docker 컨테이너 실행
      - run: docker compose up -d
        env:
          RUNNER_TRACKING_ID: ""
        
